### ISSUE TITLE
aliyun-log-flunme sink error

### ISSUE THREAD

**Issue by zhixiangjoy** [aliyun/aliyun-log-flume#3]
当我使用aliyun-log-flume 插件从kafka消费数据到loghub时，遇到如下报错：
```java 
2019-07-12 16:03:19,228 (lifecycleSupervisor-1-1) [ERROR - org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)] Unable to start SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@3663ea04 counterGroup:{ name:null counters:{} } } - Exception follows.
java.lang.NoSuchMethodError: com.google.common.hash.Hashing.farmHashFingerprint64()Lcom/google/common/hash/HashFunction;
	at com.aliyun.openservices.aliyun.log.producer.internals.Utils.generateProducerHash(Utils.java:31)
	at com.aliyun.openservices.aliyun.log.producer.LogProducer.<init>(LogProducer.java:77)
	at com.aliyun.loghub.flume.sink.LoghubSink.start(LoghubSink.java:55)
	at org.apache.flume.sink.DefaultSinkProcessor.start(DefaultSinkProcessor.java:45)
	at org.apache.flume.SinkRunner.start(SinkRunner.java:79)
	at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:249)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-12 16:03:19,230 (lifecycleSupervisor-1-1) [INFO - com.aliyun.loghub.flume.sink.LoghubSink.stop(LoghubSink.java:176)] Stopping Loghub Sink slssink
2019-07-12 16:03:19,230 (lifecycleSupervisor-1-1) [ERROR - com.aliyun.loghub.flume.sink.LoghubSink.stop(LoghubSink.java:180)] Error while closing Loghub producer of sink slssink.
java.lang.NullPointerException
	at com.aliyun.loghub.flume.sink.LoghubSink.stop(LoghubSink.java:178)
	at org.apache.flume.sink.DefaultSinkProcessor.stop(DefaultSinkProcessor.java:52)
	at org.apache.flume.SinkRunner.stop(SinkRunner.java:113)
	at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:257)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
这是我的环境信息： centos7 jdk8-1.8.0_212
我的sink配置如下：
```
kafkasourceagent.sources = r1
kafkasourceagent.channels = c1
kafkasourceagent.sinks = slssink
kafkasourceagent.sources.r1.type = org.apache.flume.source.kafka.KafkaSource 
kafkasourceagent.sources.r1.batchSize = 100
kafkasourceagent.sources.r1.batchDurationMillis = 1000
kafkasourceagent.sources.r1.kafka.bootstrap.servers = 10.100.5.211:9092
kafkasourceagent.sources.r1.kafka.topics = beats-rope 
kafkasourceagent.sources.r1.kafka.consumer.group.id = flumekafkagroupid

# Describe the sink:
kafkasourceagent.sinks.slssink.type = com.aliyun.loghub.flume.sink.LoghubSink
#kafkasourceagent.sinks.slssink.type = logger 

# vpc endpoint cn-beijing-intranet.log.aliyuncs.com
#kafkasourceagent.sinks.slssink.serializer = DELIMITED
kafkasourceagent.sinks.slssink.columns = topic,body
kafkasourceagent.sinks.slssink.separatorChar = , 
kafkasourceagent.sinks.slssink.quoteChar = '
kafkasourceagent.sinks.slssink.escapeChar = "


kafkasourceagent.sinks.slssink.endpoint = cn-beijing-intranet.log.aliyuncs.com 
kafkasourceagent.sinks.slssink.project = my-pro
kafkasourceagent.sinks.slssink.logstore = my-logstore
kafkasourceagent.sinks.slssink.accessKeyId =my-keyid
kafkasourceagent.sinks.slssink.accessKey = my-key


# Configure a channel that buffers events in memory:
kafkasourceagent.channels.c1.type = memory
kafkasourceagent.channels.c1.capacity = 100000000
kafkasourceagent.channels.c1.transactionCapacity = 100000

# Bind the source and sink to the channel:
kafkasourceagent.sources.r1.channels = c1 
kafkasourceagent.sinks.slssink.channel = c1
```
启动命令如下： /data/apps/apache-flume-1.9.0-bin/bin/flume-ng agent --conf conf --conf-file  conf/flume-loghub.conf --name kafkasourceagent  -Dflume.root.logger=INFO,console
能帮我看下问题出在哪里吗？

**Comment by liketic** [comment]
fixed in #4
